//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatelessOrderService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public System.Guid OrderItemKey { get; set; }
        public int OrderItemId { get; set; }
        public System.Guid OrderKey { get; set; }
        public System.Guid ProductKey { get; set; }
        public System.DateTime ItemAddedOn { get; set; }
        public string ItemAddedBy { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
